; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
#include "p16f690.inc"

; CONFIG
; __config 0x30D4
 __CONFIG _FOSC_INTRCIO & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF

;CONSTS
ROUNDS EQU 0X40
 
DELTA0 EQU 0XB9
DELTA1 EQU 0X79
DELTA2 EQU 0X37
DELTA3 EQU 0X9E
 
KEY0 EQU 0Xd4
KEY1 EQU 0X39
KEY2 EQU 0X83
KEY3 EQU 0X8d
KEY4 EQU 0X98
KEY5 EQU 0Xfc
KEY6 EQU 0X4a
KEY7 EQU 0Xa2
KEY8 EQU 0X71
KEY9 EQU 0X9d
KEY10 EQU 0Xd8
KEY11 EQU 0X1f
KEY12 EQU 0X52
KEY13 EQU 0X0a
KEY14 EQU 0X4b
KEY15 EQU 0Xa2 
 
;VARS
PT0 EQU 0X20	    ;4 BYTES	PUT PLAINTEXT HERE  OTHERWISE CAN BE USED FOR OTHER THINGS  (OVERWRITTEN AT CALL)
PT1 EQU 0X24	    ;4 BYTES	PUT PLAINTEXT HERE  OTHERWISE CAN BE USED FOR OTHER THINGS  (OVERWRITTEN AT CALL)
 
V0  EQU 0X28	    ;4 BYTES	GET CYPHERTEXT HERE CAN BE USED FOR OTHER THINGS    (OVERWRITTEN AT CALL)
V1  EQU 0X32	    ;4 BYTES	GET CYPHERTEXT HERE CAN BE USED FOR OTHER THINGS    (OVERWRITTEN AT CALL)
T1  EQU 0X36	    ;4 BYTES	CAN BE USED FOR OTHER THINGS    (OVERWRITTEN AT CALL)
T2  EQU 0X40	    ;4 BYTES	CAN BE USED FOR OTHER THINGS    (OVERWRITTEN AT CALL)
  
SUM EQU 0X44	    ;4 BYTES   CAN BE USED FOR OTHER THINGS	(OVERWRITTEN AT CALL)
TSUM EQU 0X48	    ;4 BYTES   CAN BE USED FOR OTHER THINGS	(OVERWRITTEN AT CALL) 

XTEALVAR EQU 0X52
KEYSEL EQU 0X53

NONCELO EQU 0X54    ;4 BYTES   COUNTER FOR NONCE DO NOT TOUCH
NONCEHI EQU 0X58    ;4 BYTES   COUNTER FOR NONCE DO NOT TOUCH

 
 
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED

;MAIN_PROG CODE                      ; let linker place main program

START:
    CLRF NONCELO
    CLRF NONCEHI

    MOVLW 0X68
    MOVWF PT0
    
    MOVLW 0X65
    MOVWF PT0+1
    
    MOVLW 0X6C
    MOVWF PT0+2
    
    MOVLW 0X6C
    MOVWF PT0+3
    
    MOVLW 0X6F
    MOVWF PT1
    
    MOVLW 0X50
    MOVWF PT1+1
    
    MOVLW 0X49
    MOVWF PT1+2
    
    MOVLW 0X43
    MOVWF PT1+3
 
    
    CALL XTEA
    
    ;INCREMENT NONCE COUNTER
    INCF NONCELO,F
    BTFSC STATUS,Z
    INCF NONCELO+1,F
    BTFSC STATUS,Z
    INCF NONCELO+2,F
    BTFSC STATUS,Z
    INCF NONCELO+3,F
    BTFSC STATUS,Z
    INCF NONCEHI,F
    BTFSC STATUS,Z
    INCF NONCEHI+1,F
    BTFSC STATUS,Z
    INCF NONCEHI+2,F
    BTFSC STATUS,Z
    INCF NONCEHI+3,F
    
    
LOOP:
    GOTO LOOP                          ; loop forever

WAITTX:
    BTFSS PIR1,TXIF
    GOTO WAITTX
    RETURN
    
XTEA:
    CLRF SUM
    CLRF SUM+1
    CLRF SUM+2
    CLRF SUM+3
    
    MOVF NONCELO,W
    MOVWF V0
    MOVF NONCELO+1,W
    MOVWF V0+1
    MOVF NONCELO+2,W
    MOVWF V0+2
    MOVF NONCELO+3,W
    MOVWF V0+3
    
    MOVF NONCEHI,W
    MOVWF V1
    MOVF NONCEHI+1,W
    MOVWF V1+1
    MOVF NONCEHI+2,W
    MOVWF V1+2
    MOVF NONCEHI+3,W
    MOVWF V1+3
    
    MOVLW ROUNDS
    MOVWF XTEALVAR
XTEALOOP:
    
    ;SUM = SUM + DELTA
    MOVLW DELTA0
    ADDWF SUM,F	
    BTFSC STATUS,C
    INCF SUM+1,F

    MOVLW DELTA1
    ADDWF SUM+1,F
    BTFSC STATUS,C
    INCF SUM+2,F

    MOVLW DELTA2
    ADDWF SUM+2,F
    BTFSC STATUS,C
    INCF SUM+3,F

    MOVLW DELTA3
    ADDWF SUM+3,F
    
    ;UPDATE V0
    
    MOVLW 0X03
    ANDWF SUM,W
    MOVWF KEYSEL
    
    ;T1 = V1 << 4
    MOVF V1,W
    MOVWF T1
    MOVF V1+1,W
    MOVWF T1+1
    MOVF V1+2,W
    MOVWF T1+2
    MOVF V1+3,W
    MOVWF T1+3
    
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    
    
    ;T2 = V1 >> 5
    MOVF V1,W
    MOVWF T2
    MOVF V1+1,W
    MOVWF T2+1
    MOVF V1+2,W
    MOVWF T2+2
    MOVF V1+3,W
    MOVWF T2+3
    
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    
    ;T2 = T1 XOR T2
    MOVF T1,W
    XORWF T2,F
    MOVF T1+1,W
    XORWF T2+1,F
    MOVF T1+2,W
    XORWF T2+2,F
    MOVF T1+3,W
    XORWF T2+3,F
    
    ;T2 = T2 + V1
    MOVF V1,W
    ADDWF T2,F
    BTFSC STATUS,C
    INCF T2+1,F
    
    MOVF V1+1,W
    ADDWF T2+1,F
    BTFSC STATUS,C
    INCF T2+2,F
    
    MOVF V1+2,W
    ADDWF T2+2,F
    BTFSC STATUS,C
    INCF T2+3,F
    
    MOVF V1+3,W
    ADDWF T2+3,F
    
    ;T1 = SUM + KEY[KEYSEL]
    MOVF SUM,W
    MOVWF T1
    MOVF SUM+1,W
    MOVWF T1+1
    MOVF SUM+2,W
    MOVWF T1+2
    MOVF SUM+3,W
    MOVWF T1+3
    
    MOVLW HIGH(KEYLUT0)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT0
    ADDWF T1,F
    BTFSC STATUS,C
    INCF T1+1,F
    
    
    MOVLW HIGH(KEYLUT1)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT1
    ADDWF T1+1,F
    BTFSC STATUS,C
    INCF T1+2,F
    
    MOVLW HIGH(KEYLUT2)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT2
    ADDWF T1+2,F
    BTFSC STATUS,C
    INCF T1+3,F
    
    MOVLW HIGH(KEYLUT3)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT3
    ADDWF T1+3,F
    
    ;T2 = T2 XOR T1
    MOVF T1,W
    XORWF T2,F
    
    MOVF T1+1,W
    XORWF T2+1,F
    
    MOVF T1+2,W
    XORWF T2+2,F
    
    MOVF T1+3,W
    XORWF T2+3,F
    
    ;V0 = V0 + T2
    MOVF T2,W
    ADDWF V0,F
    BTFSC STATUS,C
    INCF V0+1,F
    
    MOVF T2+1,W
    ADDWF V0+1,F
    BTFSC STATUS,C
    INCF V0+2,F
    
    MOVF T2+2,W
    ADDWF V0+2,F
    BTFSC STATUS,C
    INCF V0+3,F
    
    MOVF T2+3,W
    ADDWF V0+3,F
    
    ;UPDATE V1
    
    ;KEYSEL = SUM >> 11 & 3
    MOVF SUM,W
    MOVWF TSUM
    
    MOVF SUM+1,W
    MOVWF TSUM+1
    
    MOVF SUM+2,W
    MOVWF TSUM+2
    
    MOVF SUM+3,W
    MOVWF TSUM+3
    
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
     
    MOVLW 0X03
    ANDWF TSUM,W
    MOVWF KEYSEL
    
    ;T1 = V0 << 4
    MOVF V0,W
    MOVWF T1
    MOVF V0+1,W
    MOVWF T1+1
    MOVF V0+2,W
    MOVWF T1+2
    MOVF V0+3,W
    MOVWF T1+3
    
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    
    
    ;T2 = V0 >> 5
    MOVF V0,W
    MOVWF T2
    MOVF V0+1,W
    MOVWF T2+1
    MOVF V0+2,W
    MOVWF T2+2
    MOVF V0+3,W
    MOVWF T2+3
    
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    
    ;T2 = T1 XOR T2
    MOVF T1,W
    XORWF T2,F
    MOVF T1+1,W
    XORWF T2+1,F
    MOVF T1+2,W
    XORWF T2+2,F
    MOVF T1+3,W
    XORWF T2+3,F
    
    ;T2 = T2 + V0
    MOVF V0,W
    ADDWF T2,F
    BTFSC STATUS,C
    INCF T2+1,F
    
    MOVF V0+1,W
    ADDWF T2+1,F
    BTFSC STATUS,C
    INCF T2+2,F
    
    MOVF V0+2,W
    ADDWF T2+2,F
    BTFSC STATUS,C
    INCF T2+3,F
    
    MOVF V0+3,W
    ADDWF T2+3,F
    
    ;T1 = SUM + KEY[KEYSEL]
    MOVF SUM,W
    MOVWF T1
    MOVF SUM+1,W
    MOVWF T1+1
    MOVF SUM+2,W
    MOVWF T1+2
    MOVF SUM+3,W
    MOVWF T1+3
    
    MOVLW HIGH(KEYLUT0)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT0
    ADDWF T1,F
    BTFSC STATUS,C
    INCF T1+1,F
    
    MOVLW HIGH(KEYLUT1)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT1
    ADDWF T1+1,F
    BTFSC STATUS,C
    INCF T1+2,F
    
    MOVLW HIGH(KEYLUT2)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT2
    ADDWF T1+2,F
    BTFSC STATUS,C
    INCF T1+3,F
    
    
    MOVLW HIGH(KEYLUT3)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT3
    ADDWF T1+3,F
    
    ;T2 = T2 XOR T1
    MOVF T1,W
    XORWF T2,F
    
    MOVF T1+1,W
    XORWF T2+1,F
    
    MOVF T1+2,W
    XORWF T2+2,F
    
    MOVF T1+3,W
    XORWF T2+3,F
    
    ;V1 = V1 + T2
    MOVF T2,W
    ADDWF V1,F
    BTFSC STATUS,C
    INCF V1+1,F
    
    MOVF T2+1,W
    ADDWF V1+1,F
    BTFSC STATUS,C
    INCF V1+2,F
    
    MOVF T2+2,W
    ADDWF V1+2,F
    BTFSC STATUS,C
    INCF V1+3,F
    
    MOVF T2+3,W
    ADDWF V1+3,F
    
    DECFSZ XTEALVAR,F
    GOTO XTEALOOP
    
    ;V1|V0 = V1|V0 XOR PT1|PT0
    MOVF PT0,W
    XORWF V0,F
    
    MOVF PT0+1,W
    XORWF V0+1,F
    
    MOVF PT0+2,W
    XORWF V0+2,F
    
    MOVF PT0+3,W
    XORWF V0+3,F
    
    
    MOVF PT1,W
    XORWF V1,F
    
    MOVF PT1+1,W
    XORWF V1+1,F
    
    MOVF PT1+2,W
    XORWF V1+2,F
    
    MOVF PT1+3,W
    XORWF V1+3,F
    
    RETURN

ORG 0400h
KEYLUT0:
    ADDWF PCL,F
  
    RETLW KEY0
    RETLW KEY4
    RETLW KEY8
    RETLW KEY12
    
KEYLUT1:
    ADDWF PCL,F

    RETLW KEY1
    RETLW KEY5
    RETLW KEY9
    RETLW KEY13
    
KEYLUT2:
    ADDWF PCL,F
    
    RETLW KEY2
    RETLW KEY6
    RETLW KEY10
    RETLW KEY14
    
KEYLUT3:
    ADDWF PCL,F
    
    RETLW KEY3
    RETLW KEY7
    RETLW KEY11
    RETLW KEY15
    END
