; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
#include "p16f690.inc"

; CONFIG
; __config 0x30D4
 __CONFIG _FOSC_INTRCIO & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF

;CONSTS
NONCEADDR EQU 0X00 ;START ADDRESS OF NONCE IN EEPROM (8 BYTES)
 
ROUNDS EQU 0X40	;64 ROUNDS STANDARD, INSECURE BELOW 32, DIMINISHING RESULTS PAST 64
 
DELTA0 EQU 0XB9
DELTA1 EQU 0X79	    
DELTA2 EQU 0X37
DELTA3 EQU 0X9E	;STANDARD, DON'T CHANGE
 
KEY0 EQU 0Xd4
KEY1 EQU 0X39
KEY2 EQU 0X83
KEY3 EQU 0X8d
KEY4 EQU 0X98
KEY5 EQU 0Xfc
KEY6 EQU 0X4a
KEY7 EQU 0Xa2
KEY8 EQU 0X71
KEY9 EQU 0X9d	   
KEY10 EQU 0Xd8
KEY11 EQU 0X1f
KEY12 EQU 0X52
KEY13 EQU 0X0a
KEY14 EQU 0X4b
KEY15 EQU 0Xa2	;CHANGE TO YOUR OWN KEY
 
;VARS
PT0 EQU 0X20	    ;4 BYTES	PUT PLAINTEXT HERE FOR ENCRYPTION OR CIPHERTEXT FOR DECRYPTION  OTHERWISE CAN BE USED FOR OTHER THINGS  (OVERWRITTEN AT CALL)
PT1 EQU 0X24	    ;4 BYTES	PUT PLAINTEXT HERE FOR ENCRYPTION OR CIPHERTEXT FOR DECRYPTION OTHERWISE CAN BE USED FOR OTHER THINGS  (OVERWRITTEN AT CALL)
 
V0  EQU 0X28	    ;4 BYTES	GET CIPHERTEXT HERE WHEN ENCRYPTING OR PLAINTEXT WHEN DECRYPTING CAN BE USED FOR OTHER THINGS    (OVERWRITTEN AT CALL)
V1  EQU 0X2C	    ;4 BYTES	GET CIPHERTEXT HERE WHEN ENCRYPTING OR PLAINTEXT WHEN DECRYPTING CAN BE USED FOR OTHER THINGS    (OVERWRITTEN AT CALL)
T1  EQU 0X30	    ;4 BYTES	CAN BE USED FOR OTHER THINGS    (OVERWRITTEN AT CALL)
T2  EQU 0X34	    ;4 BYTES	CAN BE USED FOR OTHER THINGS    (OVERWRITTEN AT CALL)
  
SUM EQU 0X38	    ;4 BYTES   CAN BE USED FOR OTHER THINGS	(OVERWRITTEN AT CALL)
TSUM EQU 0X3C	    ;4 BYTES   CAN BE USED FOR OTHER THINGS	(OVERWRITTEN AT CALL) 

XTEALVAR EQU 0X40
KEYSEL EQU 0X44

NONCELO EQU 0X48    ;4 BYTES   COUNTER FOR NONCE ALSO STORE IN EEPROM, WHEN ENCRYPTING INCREMENT AFTER EVERY PACKET, WHEN DECRYPTING SET TO THE NONCE FROM THE RECEIVED PACKET
NONCEHI EQU 0X4C    ;4 BYTES   COUNTER FOR NONCE ALSO STORE IN EEPROM, WHEN ENCRYPTING INCREMENT AFTER EVERY PACKET, WHEN DECRYPTING SET TO THE NONCE FROM THE RECEIVED PACKET

 
 
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED

;MAIN_PROG CODE                      ; let linker place main program

START:
    
    BSF STATUS,RP0
    BSF OSCCON,IRCF0
    BCF STATUS,RP0
    
    CLRF NONCELO
    CLRF NONCELO+1
    CLRF NONCELO+2
    CLRF NONCELO+3
    CLRF NONCEHI   ;CLEARING FOR TESTING IN NORMAL OPERATION GET NONCE FROM EEPROM (USING THE BELOW SEQUENCE)
    CLRF NONCEHI+1
    CLRF NONCEHI+2
    CLRF NONCEHI+3
    
    
    ;RESTORE NONCE COUNTER FROM EEPROM
;    BSF STATUS,RP1
;    
;    MOVLW NONCEADDR
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO
;    
;    
;    MOVLW NONCEADDR+1
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO+1
;    
;    
;    MOVLW NONCEADDR+2
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO+2
;    
;    
;    MOVLW NONCEADDR+3
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO+3
;    
;    
;    MOVLW NONCEADDR+4
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCEHI
;    
;    
;    MOVLW NONCEADDR+5
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCEHI+1
;    
;    
;    MOVLW NONCEADDR+6
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCEHI+2
;    
;    
;    MOVLW NONCEADDR+7
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO+3
;    
;    BCF STATUS,RP1
       
    
    
    
    ;+------------------+
    ;|	ENCRYPTION DEMO	|
    ;+------------------+
    
    ;NONCEHI|NONCELO - 64 BIT COUNTER USED AS NONCE
    ;PUT YOUR PLAINTEXT IN PT1|PT0
    ;CALL XTEA
    ;V1|V0 WILL BE THE CIPHERTEXT
    ;TX PACKET NONECEHI|NONCELO|V1|V0
    
    MOVLW 0X68
    MOVWF PT0
    
    MOVLW 0X65
    MOVWF PT0+1
    
    MOVLW 0X6C
    MOVWF PT0+2
    
    MOVLW 0X6C
    MOVWF PT0+3
    
    MOVLW 0X6F
    MOVWF PT1
    
    MOVLW 0X50
    MOVWF PT1+1
    
    MOVLW 0X49
    MOVWF PT1+2
    
    MOVLW 0X43
    MOVWF PT1+3
    
    CALL XTEA
    
    ;TRANSMIT PACKET NONCELO|NONCEHI|V1|V0
    
    ;INCREMENT NONCE COUNTER
    INCF NONCELO,F
    BTFSC STATUS,C
    INCF NONCELO+1,F
    BTFSC STATUS,C
    INCF NONCELO+2,F
    BTFSC STATUS,C
    INCF NONCELO+3,F
    BTFSC STATUS,C
    INCF NONCEHI,F
    BTFSC STATUS,C
    INCF NONCEHI+1,F
    BTFSC STATUS,C
    INCF NONCEHI+2,F
    BTFSC STATUS,C
    INCF NONCEHI+3,F
    
    ;TO AVOID REPEATING THE NONCE, STORE IT IN EEPROM
;    BSF STATUS,RP1
;    
;    MOVLW NONCEADDR
;    MOVWF EEADR
;    MOVF NONCELO,W
;    MOVWF EEDAT
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,WREN
;    
;    ;BCF INTCON,GIE
;    
;    MOVLW 0X55
;    MOVWF EECON2
;    MOVLW 0XAA
;    MOVWF EECON2
;    
;    BSF EECON1,WR
;    
;    ;BSF INTCON,GIE
;    
;    CALL WAITEEWR
;    
;    BCF STATUS,RP0
;    
;    
;    MOVLW NONCEADDR+1
;    MOVWF EEADR
;    MOVF NONCELO+1,W
;    MOVWF EEDAT
;    
;    BSF STATUS,RP0
;    
;;    BCF EECON1,EEPGD
;;    BSF EECON1,WREN
;    
;    ;BCF INTCON,GIE
;    
;    MOVLW 0X55
;    MOVWF EECON2
;    MOVLW 0XAA
;    MOVWF EECON2
;    
;    BSF EECON1,WR
;    
;    ;BSF INTCON,GIE
;    
;    CALL WAITEEWR
;    
;    BCF STATUS,RP0
;    
;    
;    MOVLW NONCEADDR+2
;    MOVWF EEADR
;    MOVF NONCELO+2,W
;    MOVWF EEDAT
;    
;    BSF STATUS,RP0
;    
;;    BCF EECON1,EEPGD
;;    BSF EECON1,WREN
;    
;    ;BCF INTCON,GIE
;    
;    MOVLW 0X55
;    MOVWF EECON2
;    MOVLW 0XAA
;    MOVWF EECON2
;    
;    BSF EECON1,WR
;    
;    ;BSF INTCON,GIE
;    
;    CALL WAITEEWR
;    
;    BCF STATUS,RP0
;    
;    
;    MOVLW NONCEADDR+3
;    MOVWF EEADR
;    MOVF NONCELO+3,W
;    MOVWF EEDAT
;    
;    BSF STATUS,RP0
;    
;;    BCF EECON1,EEPGD
;;    BSF EECON1,WREN
;    
;    ;BCF INTCON,GIE
;    
;    MOVLW 0X55
;    MOVWF EECON2
;    MOVLW 0XAA
;    MOVWF EECON2
;    
;    BSF EECON1,WR
;    
;    ;BSF INTCON,GIE
;    
;    CALL WAITEEWR
;    
;    BCF STATUS,RP0
;    
;    
;    MOVLW NONCEADDR+4
;    MOVWF EEADR
;    MOVF NONCEHI,W
;    MOVWF EEDAT
;    
;    BSF STATUS,RP0
;    
;;    BCF EECON1,EEPGD
;;    BSF EECON1,WREN
;    
;    ;BCF INTCON,GIE
;    
;    MOVLW 0X55
;    MOVWF EECON2
;    MOVLW 0XAA
;    MOVWF EECON2
;    
;    BSF EECON1,WR
;    
;    ;BSF INTCON,GIE
;    
;    CALL WAITEEWR
;    
;    BCF STATUS,RP0
;    
;    
;    MOVLW NONCEADDR+5
;    MOVWF EEADR
;    MOVF NONCEHI+1,W
;    MOVWF EEDAT
;    
;    BSF STATUS,RP0
;    
;;    BCF EECON1,EEPGD
;;    BSF EECON1,WREN
;    
;    ;BCF INTCON,GIE
;    
;    MOVLW 0X55
;    MOVWF EECON2
;    MOVLW 0XAA
;    MOVWF EECON2
;    
;    BSF EECON1,WR
;    
;    ;BSF INTCON,GIE
;    
;    CALL WAITEEWR
;    
;    BCF STATUS,RP0
;    
;    
;    MOVLW NONCEADDR+6
;    MOVWF EEADR
;    MOVF NONCEHI+2,W
;    MOVWF EEDAT
;    
;    BSF STATUS,RP0
;    
;;    BCF EECON1,EEPGD
;;    BSF EECON1,WREN
;    
;    ;BCF INTCON,GIE
;    
;    MOVLW 0X55
;    MOVWF EECON2
;    MOVLW 0XAA
;    MOVWF EECON2
;    
;    BSF EECON1,WR
;    
;    ;BSF INTCON,GIE
;    
;    CALL WAITEEWR
;    
;    BCF STATUS,RP0
;    
;    
;    MOVLW NONCEADDR+7
;    MOVWF EEADR
;    MOVF NONCEHI+3,W
;    MOVWF EEDAT
;    
;    BSF STATUS,RP0
;    
;;    BCF EECON1,EEPGD
;;    BSF EECON1,WREN
;    
;    ;BCF INTCON,GIE
;    
;    MOVLW 0X55
;    MOVWF EECON2
;    MOVLW 0XAA
;    MOVWF EECON2
;    
;    BSF EECON1,WR
;    
;    ;BSF INTCON,GIE
;    
;    CALL WAITEEWR
;    
;    BCF EECON1,WREN
;    BCF STATUS,RP0
;    BCF STATUS,RP1
    
    
    
    
    
    ;+------------------+
    ;|	DECRYPTION DEMO	|
    ;+------------------+
    
    ;RX PACKET NONECEHI|NONCELO|DATA1|DATA0
    ;NONCELO = RX_NONCELO
    ;NONCEHI = RX_NONCEHI
    ;PT0 = RX_DATA0
    ;PT1 = RX_DATA1
    ;CALL XTEA
    ;V1|V0 WILL BE THE PLAINTEXT
    
    CLRF NONCELO
    CLRF NONCELO+1
    CLRF NONCELO+2
    CLRF NONCELO+3
    CLRF NONCEHI	;(CLEARED FOR TESTING)
    CLRF NONCEHI+1
    CLRF NONCEHI+2
    CLRF NONCEHI+3
    
    MOVLW 0XD1
    MOVWF PT0
    MOVLW 0XF9
    MOVWF PT0+1
    MOVLW 0XCB
    MOVWF PT0+2
    MOVLW 0XEB
    MOVWF PT0+3
    
    MOVLW 0X2B
    MOVWF PT1
    MOVLW 0XAF
    MOVWF PT1+1
    MOVLW 0X13
    MOVWF PT1+2
    MOVLW 0X7F
    MOVWF PT1+3
    
    CALL XTEA

    ;RESTORE NONCE COUNTER FROM EEPROM
;    BSF STATUS,RP1
;    
;    MOVLW NONCEADDR
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO
;    
;    
;    MOVLW NONCEADDR+1
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO+1
;    
;    
;    MOVLW NONCEADDR+2
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO+2
;    
;    
;    MOVLW NONCEADDR+3
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO+3
;    
;    
;    MOVLW NONCEADDR+4
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCEHI
;    
;    
;    MOVLW NONCEADDR+5
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCEHI+1
;    
;    
;    MOVLW NONCEADDR+6
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCEHI+2
;    
;    
;    MOVLW NONCEADDR+7
;    MOVWF EEADDR
;    
;    BSF STATUS,RP0
;    
;    BCF EECON1,EEPGD
;    BSF EECON1,RD
;    
;    BCF STATUS,RP0
;    
;    MOVF EEDAT,W
;    MOVFW NONCELO+3
;    
;    BCF STATUS,RP1
    
    
LOOP:
    GOTO LOOP                          ; loop forever

    
    
WAITEEWR:
    BTFSC EECON1,WR
    GOTO WAITEEWR
    RETURN
    
XTEA:
    CLRF SUM
    CLRF SUM+1
    CLRF SUM+2
    CLRF SUM+3
    
    MOVF NONCELO,W
    MOVWF V0
    MOVF NONCELO+1,W
    MOVWF V0+1
    MOVF NONCELO+2,W
    MOVWF V0+2
    MOVF NONCELO+3,W
    MOVWF V0+3
    
    MOVF NONCEHI,W
    MOVWF V1
    MOVF NONCEHI+1,W
    MOVWF V1+1
    MOVF NONCEHI+2,W
    MOVWF V1+2
    MOVF NONCEHI+3,W
    MOVWF V1+3
    
    MOVLW ROUNDS
    MOVWF XTEALVAR
XTEALOOP:
    
    ;SUM = SUM + DELTA
    MOVLW DELTA0
    ADDWF SUM,F	
    BTFSC STATUS,C
    INCF SUM+1,F

    MOVLW DELTA1
    ADDWF SUM+1,F
    BTFSC STATUS,C
    INCF SUM+2,F

    MOVLW DELTA2
    ADDWF SUM+2,F
    BTFSC STATUS,C
    INCF SUM+3,F

    MOVLW DELTA3
    ADDWF SUM+3,F
    
    ;UPDATE V0
    
    MOVLW 0X03
    ANDWF SUM,W
    MOVWF KEYSEL
    
    ;T1 = V1 << 4
    MOVF V1,W
    MOVWF T1
    MOVF V1+1,W
    MOVWF T1+1
    MOVF V1+2,W
    MOVWF T1+2
    MOVF V1+3,W
    MOVWF T1+3
    
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    
    
    ;T2 = V1 >> 5
    MOVF V1,W
    MOVWF T2
    MOVF V1+1,W
    MOVWF T2+1
    MOVF V1+2,W
    MOVWF T2+2
    MOVF V1+3,W
    MOVWF T2+3
    
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    
    ;T2 = T1 XOR T2
    MOVF T1,W
    XORWF T2,F
    MOVF T1+1,W
    XORWF T2+1,F
    MOVF T1+2,W
    XORWF T2+2,F
    MOVF T1+3,W
    XORWF T2+3,F
    
    ;T2 = T2 + V1
    MOVF V1,W
    ADDWF T2,F
    BTFSC STATUS,C
    INCF T2+1,F
    
    MOVF V1+1,W
    ADDWF T2+1,F
    BTFSC STATUS,C
    INCF T2+2,F
    
    MOVF V1+2,W
    ADDWF T2+2,F
    BTFSC STATUS,C
    INCF T2+3,F
    
    MOVF V1+3,W
    ADDWF T2+3,F
    
    ;T1 = SUM + KEY[KEYSEL]
    MOVF SUM,W
    MOVWF T1
    MOVF SUM+1,W
    MOVWF T1+1
    MOVF SUM+2,W
    MOVWF T1+2
    MOVF SUM+3,W
    MOVWF T1+3
    
    MOVLW HIGH(KEYLUT0)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT0
    ADDWF T1,F
    BTFSC STATUS,C
    INCF T1+1,F
    
    
    MOVLW HIGH(KEYLUT1)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT1
    ADDWF T1+1,F
    BTFSC STATUS,C
    INCF T1+2,F
    
    MOVLW HIGH(KEYLUT2)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT2
    ADDWF T1+2,F
    BTFSC STATUS,C
    INCF T1+3,F
    
    MOVLW HIGH(KEYLUT3)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT3
    ADDWF T1+3,F
    
    ;T2 = T2 XOR T1
    MOVF T1,W
    XORWF T2,F
    
    MOVF T1+1,W
    XORWF T2+1,F
    
    MOVF T1+2,W
    XORWF T2+2,F
    
    MOVF T1+3,W
    XORWF T2+3,F
    
    ;V0 = V0 + T2
    MOVF T2,W
    ADDWF V0,F
    BTFSC STATUS,C
    INCF V0+1,F
    
    MOVF T2+1,W
    ADDWF V0+1,F
    BTFSC STATUS,C
    INCF V0+2,F
    
    MOVF T2+2,W
    ADDWF V0+2,F
    BTFSC STATUS,C
    INCF V0+3,F
    
    MOVF T2+3,W
    ADDWF V0+3,F
    
    ;UPDATE V1
    
    ;KEYSEL = SUM >> 11 & 3
    MOVF SUM,W
    MOVWF TSUM
    
    MOVF SUM+1,W
    MOVWF TSUM+1
    
    MOVF SUM+2,W
    MOVWF TSUM+2
    
    MOVF SUM+3,W
    MOVWF TSUM+3
    
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
    RRF TSUM+3,F
    RRF TSUM+2,F
    RRF TSUM+1,F
    RRF TSUM,F
    BCF STATUS,C
     
    MOVLW 0X03
    ANDWF TSUM,W
    MOVWF KEYSEL
    
    ;T1 = V0 << 4
    MOVF V0,W
    MOVWF T1
    MOVF V0+1,W
    MOVWF T1+1
    MOVF V0+2,W
    MOVWF T1+2
    MOVF V0+3,W
    MOVWF T1+3
    
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    RLF T1,F
    RLF T1+1,F
    RLF T1+2,F
    RLF T1+3,F
    BCF STATUS,C
    
    
    ;T2 = V0 >> 5
    MOVF V0,W
    MOVWF T2
    MOVF V0+1,W
    MOVWF T2+1
    MOVF V0+2,W
    MOVWF T2+2
    MOVF V0+3,W
    MOVWF T2+3
    
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    RRF T2+3,F
    RRF T2+2,F
    RRF T2+1,F
    RRF T2,F
    BCF STATUS,C
    
    ;T2 = T1 XOR T2
    MOVF T1,W
    XORWF T2,F
    MOVF T1+1,W
    XORWF T2+1,F
    MOVF T1+2,W
    XORWF T2+2,F
    MOVF T1+3,W
    XORWF T2+3,F
    
    ;T2 = T2 + V0
    MOVF V0,W
    ADDWF T2,F
    BTFSC STATUS,C
    INCF T2+1,F
    
    MOVF V0+1,W
    ADDWF T2+1,F
    BTFSC STATUS,C
    INCF T2+2,F
    
    MOVF V0+2,W
    ADDWF T2+2,F
    BTFSC STATUS,C
    INCF T2+3,F
    
    MOVF V0+3,W
    ADDWF T2+3,F
    
    ;T1 = SUM + KEY[KEYSEL]
    MOVF SUM,W
    MOVWF T1
    MOVF SUM+1,W
    MOVWF T1+1
    MOVF SUM+2,W
    MOVWF T1+2
    MOVF SUM+3,W
    MOVWF T1+3
    
    MOVLW HIGH(KEYLUT0)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT0
    ADDWF T1,F
    BTFSC STATUS,C
    INCF T1+1,F
    
    MOVLW HIGH(KEYLUT1)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT1
    ADDWF T1+1,F
    BTFSC STATUS,C
    INCF T1+2,F
    
    MOVLW HIGH(KEYLUT2)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT2
    ADDWF T1+2,F
    BTFSC STATUS,C
    INCF T1+3,F
    
    
    MOVLW HIGH(KEYLUT3)
    MOVWF PCLATH
    MOVF KEYSEL,W
    CALL KEYLUT3
    ADDWF T1+3,F
    
    ;T2 = T2 XOR T1
    MOVF T1,W
    XORWF T2,F
    
    MOVF T1+1,W
    XORWF T2+1,F
    
    MOVF T1+2,W
    XORWF T2+2,F
    
    MOVF T1+3,W
    XORWF T2+3,F
    
    ;V1 = V1 + T2
    MOVF T2,W
    ADDWF V1,F
    BTFSC STATUS,C
    INCF V1+1,F
    
    MOVF T2+1,W
    ADDWF V1+1,F
    BTFSC STATUS,C
    INCF V1+2,F
    
    MOVF T2+2,W
    ADDWF V1+2,F
    BTFSC STATUS,C
    INCF V1+3,F
    
    MOVF T2+3,W
    ADDWF V1+3,F
    
    DECFSZ XTEALVAR,F
    GOTO XTEALOOP
    
    ;V1|V0 = V1|V0 XOR PT1|PT0
    MOVF PT0,W
    XORWF V0,F
    
    MOVF PT0+1,W
    XORWF V0+1,F
    
    MOVF PT0+2,W
    XORWF V0+2,F
    
    MOVF PT0+3,W
    XORWF V0+3,F
    
    
    MOVF PT1,W
    XORWF V1,F
    
    MOVF PT1+1,W
    XORWF V1+1,F
    
    MOVF PT1+2,W
    XORWF V1+2,F
    
    MOVF PT1+3,W
    XORWF V1+3,F
    
    RETURN

ORG 0400h
KEYLUT0:
    ADDWF PCL,F
  
    RETLW KEY0
    RETLW KEY4
    RETLW KEY8
    RETLW KEY12
    
KEYLUT1:
    ADDWF PCL,F

    RETLW KEY1
    RETLW KEY5
    RETLW KEY9
    RETLW KEY13
    
KEYLUT2:
    ADDWF PCL,F
    
    RETLW KEY2
    RETLW KEY6
    RETLW KEY10
    RETLW KEY14
    
KEYLUT3:
    ADDWF PCL,F
    
    RETLW KEY3
    RETLW KEY7
    RETLW KEY11
    RETLW KEY15
    END
